name: data_layer
description: Data layer
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  dio: ^4.0.4
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer_layer:
    path: ../analyzer_layer
  lint: ^1.5.0
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.10.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
